# This is a basic workflow to help you get started with Actions

name: CI

on:
 workflow_dispatch:
    inputs:
      repo:
         # Repository name with owner. For example, VirtoCommerce/platform
        description: 'repository'
        required: true
      ref:
         # The branch. For example, master
        description: 'repository branch'
        required: true



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo "repo ${{ github.event.inputs.repo }}"
        echo "branch ${{ github.event.inputs.ref }}"
     
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.repo }}
        ref: ${{ github.event.inputs.ref }}
        token: ${{ secrets.WEBHOOK }}
